### ISSUE TITLE
How to train the object

### ISSUE THREAD

**Issue by santhoshnp** [ssp4all/faceRecognition#1]
It is not an issue but it is doubtful. I am using raspberry pi zero how to train the object. can you please help me

**Comment by ssp4all** [comment]
1->Install all dependencies which are imported, like open-cv, bs4, requests etc.
2-> Run this file [Main program](https://github.com/ssp4all/faceRecognition/blob/master/faceRecognizeMain.py)
3-> Done

**Comment by santhoshnp** [comment]
Thank you for your response
1) It will send the photo to mail
